USE RaisingPet;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE StockPrice;
TRUNCATE TABLE StockTrade;
TRUNCATE TABLE StockSale;
TRUNCATE TABLE StockHolding;
TRUNCATE TABLE Stock;
TRUNCATE TABLE PlayerLoan;
TRUNCATE TABLE PlayerSavings;
TRUNCATE TABLE Player;

SET FOREIGN_KEY_CHECKS = 1;